version: "3.9"

services:
  backend:
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    volumes:
      - ./backend:/app

  frontend:
    environment:
      - REACT_APP_API_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
