version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/backend
    depends_on:
      - db

volumes:
  db_data:
