name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          docker compose -v
      # 3️⃣ Build all Docker images
      - name: Build Docker Compose services
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build

      # 4️⃣ Run backend tests inside container
      - name: Run backend tests
        run: |
           docker compose up -d db
           docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm backend \ dotnet test /src/backend.Tests/backend.Tests.csproj --no-build -c Releas
       
              
      