name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build Docker Compose services
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build

      - name: Run backend tests
        working-directory: ${{ github.workspace }}
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm backend dotnet test /src/backend.Tests/backend.Tests.csproj --no-build -c Release

      - name: Run frontend build
        working-directory: ${{ github.workspace }}
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm ci
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm frontend npm run build

      - name: Lint Dockerfiles
        working-directory: ${{ github.workspace }}
        run: |
          docker run --rm -i hadolint/hadolint < backend/Dockerfile || true
          docker run --rm -i hadolint/hadolint < frontend/Dockerfile || true
